---
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get update -y
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - make docker-build
  post_build:
    commands:
      - make docker-push
