name                                                = "squid"
ssm_kms_key_arn                                     = ""
ecs_task_iam_policy_attachment_arns_count           = 0
ecs_task_iam_policy_attachment_arns                 = []
create_ecs_cluster                                  = true
ecs_cluster_name                                    = "infrastructure-services"
#container_def_image                                 = ""
squid_conf_ssm_parameter_name                       = "/docker-squid/env/dev/etc/squid/squid.conf"
squid_whitelist_ssm_parameter_name                  = "/docker-squid/env/dev/etc/squid/squid.whitelist"
ecs_service_assign_public_ip                        = true
ecs_service_desired_count                           = 2
ecs_service_security_group_attachments              = ["sg-08c053091f1eb8465"]
ecs_service_subnets                                 = ["subnet-0fefcef754399a653", "subnet-0ba6189d0bb0ba043"]
create_service_discovery_dns_namespace              = true
service_discovery_private_dns_namespace_id          = ""
service_discovery_private_dns_namespace_name        = "infra-svc.ews.works"
service_discovery_private_dns_namespace_description = "infrastructure services"
service_discovery_private_dns_namespace_vpc_id      = "vpc-090fb2bb569edbd85"
